name: CI/CD with GCE version 1

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 10.19.0

    - name: Install dependencies
      run: npm install 
    
    - name: Build Artifact
      run: npm run build
      
    - name: Archive Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: nodeapp-artifact
        path: ${{ github.workspace }}

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:

    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: nodeapp-artifact
        path: ${{ github.workspace }}

    - name: Display structure of downloaded files
      run: ls -R
      working-directory: /home/runner/work/node-app-githubactions/node-app-githubactions
      

    - name: Copy artifact to host machine
      run: |
        scp -i ${{ secrets.GCE_SSH_KEY }} -r ${{ github.workspace }}/node-app-githubactions ${{ secrets.GCE_USERNAME }}@${{ secrets.GCE_HOST }}:/home/${{ secrets.GCE_USERNAME }}/node-app-githubactions
      


    # - name: Extract artifact
    #   run: |
    #     tar -xvf /home/runner/work/node-app-githubactions/node-app-githubactions/nodeapp-artifact.tar.gz -C /home/${{ secrets.GCE_USERNAME }}    

    - name: SSH into GCE and deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.GCE_HOST }}
        username: ${{ secrets.GCE_USERNAME }}
        key: ${{ secrets.GCE_SSH_KEY }}
        port: 22
        script: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.GCE_HOST }} >> ~/.ssh/known_hosts
          cd /home/${{ secrets.GCE_USERNAME }}/node-app-githubactions
          pm2 stop nodeapp
          pm2 start /home/${{ secrets.GCE_USERNAME }}/node-app-githubactions/app.js -f --name nodeapp
          pm2 restart nodeapp
          pm2 save
