name: CI/CD with GCE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 10.19.0

    - name: Install dependencies
      run: npm install 

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: SSH into GCE and deploy
      uses: appleboy/ssh-action@v0.7.0
      with:
        host: ${{ secrets.GCE_HOST }}
        username: ${{ secrets.GCE_USERNAME }}
        key: ${{ secrets.GCE_SSH_KEY }}
        port: 22
        script: |
          cd node-app-githubactions/
          git pull https://github.com/alifarhat-eurus/node-app-githubactions.git
          npm install 
          node app.js
