name: CI/CD with GCE version 1 and 2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 10.19.0

    - name: Install dependencies
      run: npm install 

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: SSH into GCE and deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.GCE_HOST }}
        username: ${{ secrets.GCE_USERNAME }}
        key: ${{ secrets.GCE_SSH_KEY }}
        port: 22
        script: |
          cd /home/${{ secrets.GCE_USERNAME }}
          git clone https://github.com/alifarhat-${{ secrets.GCE_USERNAME }}/node-app-githubactions.git && cd node-app-githubactions/ && npm install && npm install -g pm2 
          pm2 start /home/${{ secrets.GCE_USERNAME }}/node-app-githubactions/app.js -f --name nodeapp
          pm2 save
